name: Maestro
on:
  push:
    branches:
      - main
env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 31
  ANDROID_BUILD_TOOLS_VERSION: 31.0.0
  ANDROID_SDK_PACKAGES: system-images;android-31;google_apis_playstore;x86_64 platforms;android-31 build-tools;31.0.0 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: maestro
  MAESTRO_DRIVER_STARTUP_TIMEOUT: 60000
jobs:
  maestro:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          echo $ANDROID_HOME/cmdline-tools/latest/bin >> $GITHUB_PATH
          echo $ANDROID_HOME/platform-tools >> $GITHUB_PATH
          echo $ANDROID_HOME/emulator >> $GITHUB_PATH
          echo $ANDROID_HOME/tools >> $GITHUB_PATH
          echo $ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }} >> $GITHUB_PATH
          echo $HOME/.maestro/bin >> $GITHUB_PATH
      - name: Install Android SDK packages and accept licenses
        run: |
          yes Y | sdkmanager --licenses
          sdkmanager --install $ANDROID_SDK_PACKAGES
      - name: Create Android Virtual Device
        run: echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "${ANDROID_TARGET}/${ANDROID_ARCH}" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"
      - name: Run Android Virtual Device
        run: |
          chmod +x ./maestro/run_android_emulator.sh
          EMULATOR_NAME=$EMULATOR_NAME ./maestro/run_android_emulator.sh
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.24.4
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter build apk
      - run: curl -fsSL "https://get.maestro.mobile.dev" | bash
      - name: Check Android Virtual Device
        run: |
          chmod +x ./maestro/check_android_emulator.sh
          EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT ./maestro/check_android_emulator.sh
      - run: flutter install
      - run: maestro test maestro/launch.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: maestro
          path: $HOME/.maestro/tests/
